//module1.js 
let World_Research =
{
	name1: "Alabama",
	name2: "Alaska",
	name3: "Arizona",
	name4: "Arkansas",
	name5: "California",
	name6: "Colorado",
	name7: "Connecticut",
	name8: "Delaware",
	name9: "Florida",
	name10: "Georgia",
	name11: "Hawaii",
	name12: "Idaho",
	name13: "Illinois",
	name14: "Indiana",
	name15: "Iowa",
	name16: "Kansas",
	name17: "Kentucky",
	name18: "Louisiana",
	name19: "Maine",
	name20: "Maryland",
	name21: "Massachusetts",
	name22: "Michigan",
	name23: "Minnesota",
	name24: "Mississippi",
	name25: "Missouri",
	name26: "Montana",
	name27: "Nebraska",
	name28: "Nevada",
	name29: "New Hampshire",
	name30: "New Jersey",
	name31: "New Mexico",
	name32: "New York",
	name33: "North Carolina",
	name34: "North Dakota",
	name35: "Ohio",
	name36: "Oklahoma",
	name37: "Oregon",
	name38: "Pennsylvania",
	name39: "Rhode Island",
	name40: "South Carolina",
	name41: "South Dakota",
	name42: "Tennessee",
	name43: "Texas",
	name44: "Utah",
	name45: "Vermont",
	name46: "Virginia",
	name47: "Washington",
	name48: "West Virginia",
	name49: "Wisconsin",
	name50: "Wyoming",
	/*
	name51: "American Foxhound",
	name52: "American Leopard Hound",
	name53: "American Pit Bull Terrier",
	name54: "American Pygmy Goat",
	name55: "American Staffordshire Terrier",
	name56: "American Water Spaniel",
	name57: "Amethystine Python",
	name58: "Amur Leopard",
	name59: "Anatolian Shepherd Dog",
	name60: "Andrewsarchus",
	name61: "Angelshark",
	name62: "Anglerfish",
	name63: "Anna’s Hummingbird",
	name64: "Anomalocaris",
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};