# These are supported funding model platforms

github: blaccenterprise
patreon: blaccenterprise
ko_fi: blaccenterprise
liberapay: BLACC_CORPORATION
polar: blacc-corporation
buy_me_a_coffee: blaccenterprise
thanks_dev: u/gh/blaccenterprise
custom: ['https://blacccorp.com',]
