//module1.js 
let Database =
{
	name1: "Alhambra",
	name2: "Azusa",
	name3: "Baldwin Park",
	name4: "Covina",
	name5: "Diamond Bar",
	name6: "El Monte",
	name7: "Industry",
	name8: "Irwindale",
	name9: "La Puente",
	name10: "Los Angeles",
	name11: "Montobello",
	name12: "Pomona",
	name13: "Rosemead",
	name14: "San Gabriel",
	name15: "South El Monte",
	name16: "Walnut",
	name17: "West Covina",
	name18: "Agoura Hills",
	name19: "Beverly Hills",
	name20: "Calabasas",
	name21: "Carson",
	name22: "Compton",
	name23: "Culver City",
	name24: "El Segundo",
	name25: "Gardena",
	name26: "Hawthorne",
	name27: "Hermosa Beach",
	name28: "Hidden Hills",
	name29: "Inglewood",
	name30: "Lawndale",
	name31: "Malibu",
	name32: "Manhattan Beach",
	name33: "Redondo Beach",
	name34: "San Fernando",
	name35: "Santa Monica",
	name36: "West Hollywood",
	name37: "Westlake Village",
	name38: "Avalon",
	name39: "Bell",
	name40: "Bell Gardens",
	name41: "Bellflower",
	name42: "Commerce",
	name43: "Cudahy",
	name44: "Downey",
	name45: "Huntington Park",
	name46: "La Habra Height",
	name47: "La Mirada",
	name48: "Lakewood",
	name49: "Lomita",
	name50: "Long Beach",
	name51: "Lynwood",
	name52: "Maywood",
	name53: "Norwalk",
	name54: "Palos Verdes Estate",
	name55: "Paramount",
	name56: "Pico Rivera",
	name57: "Rancho Palo Verdes",
	name58: "Rolling Hills",
	name59: "San Catalina Island",
	name60: "San Clemente Island",
	name61: "Santa Fe Springs",
	name62: "Signal Hills",
	name63: "South Gate",
	name64: "Torrance",
	name65: "Vernon",
	name66: "Whittier",
	name67: "Arcadia",
	name68: "Bradbury",
	name69: "Burbank",
	name70: "Claremont",
	name71: "Duarte",
	name72: "Glendale",
	name73: "Glendora",
	name74: "La Canada Flintridge",
	name75: "La Verne",
	name76: "Lancaster",
	name77: "Monrovia",
	name78: "Palmdale",
	name79: "Pasadena",
	name80: "San Dimas",
	name81: "San Marino",
	name82: "Santa Clarita",
	name83: "South Pasadena",
	name84: "Sierra Madre",
	name85: "Temple City",
	name86: "Boulder City",
	name87: "Bunkerville",
	name88: "Cal Nev Ari",
	name89: "Corn Creek",
	name90: "Coyotte Springs",
	name91: "Echo Bay",
	name92: "Henderson",
	name93: "Indian Springs",
	name94: "Jean",
	name95: "Las Vegas",
	name96: "Laughlin",
	name97: "Moapa Valley",
	name98: "Mosquite",
	name99: "Overturn",
	name100: "Primm",
	name101: "Sandy Valley",
	name102: "Searchlight",
	name103: "Sloan",
	name104: "Southern Desert Correctional Center",
	name105: "Lawrencium",
	name106: "Rutherfordium",
	name107: "Dubnium",
	name108: "Seaborgium",
	name109: "Bohrium",
	name110: "Hassium",
	name111: "Meitnerium",
	name112: "Darmstadtium",
	name113: "Roentgenium",
	name114: "Copernicium",
	name115: "Ununtrium",
	name116: "Flerovium",
	name117: "Ununpentium",
	name118: "Livermorium",
	name119: "Ununseptium",
	name120: "Ununoctium",
};