//module1.js 
let BLACCMembers =
{
	name1: "David Bush",
	name2: "Andre Saunders",
	name3: "Mariyah Townsend",
	name4: "Baby D",
	name5: "Cornell Lawson",
	name6: "Reggie",
	name7: "Elijah Richardson",
	name8: "Stephen Guevara",
	name9: "Terrell Blue",
	name10: "Jauteanna Shoe",
	name11: "Val Moore",
	name12: "Erica Davis",
	name13: "Amber Blue",
	name14: "Donye Stovall",
	name15: "Terrianne Jackson",
	name16: "Sierus Dunbar",
	name17: "Arcuist Gilbert",
	name18: "Baldwin",
	name19: "Vernon",
	/*
	name20: "African Bullfrog",
	name21: "African Civet",
	name22: "African Fish Eagle",
	name23: "African Golden Cat",
	name24: "African Jacana",
	name25: "African Penguin",
	name26: "African Tree Toad",
	name27: "African Wild Dog",
	name28: "Agama Lizard",
	name29: "Agouti",
	name30: "Ainu",
	name31: "Airedoodle",
	name32: "Akita",
	name33: "Alabai (Central Asian Shepherd)",
	name34: "Alaskan Klee Kai",
	name35: "Alaskan Pollock",
	name36: "Albacore Tuna",
	name37: "Albertonectes",
	name38: "Aldabra Giant Tortoise",
	name39: "Allosaurus",
	name40: "Alpaca",
	name41: "Alpine Goat",
	name42: "Amano Shrimp",
	name43: "Amazon Parrot",
	name44: "Amazon Tree Boa",
	name45: "Amberjack",
	name46: "American Alligator",
	name47: "American Bulldog",
	name48: "American Cocker Spaniel",
	name49: "American Coonhound",
	name50: "American Eel",
	name51: "American Foxhound",
	name52: "American Leopard Hound",
	name53: "American Pit Bull Terrier",
	name54: "American Pygmy Goat",
	name55: "American Staffordshire Terrier",
	name56: "American Water Spaniel",
	name57: "Amethystine Python",
	name58: "Amur Leopard",
	name59: "Anatolian Shepherd Dog",
	name60: "Andrewsarchus",
	name61: "Angelshark",
	name62: "Anglerfish",
	name63: "Anna’s Hummingbird",
	name64: "Anomalocaris",
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};