//module1.js 
let ASL =
{
	name1: "A",
	name2: "B",
	name3: "C",
	name4: "D",
	name5: "E",
	name6: "F",
	name7: "G",
	name8: "H",
	name9: "I",
	name10: "J",
	name11: "K",
	name12: "L",
	name13: "M",
	name14: "N",
	name15: "O",
	name16: "P",
	name17: "Q",
	name18: "R",
	name19: "S",
	name20: "T",
	name21: "U",
	name22: "V",
	name23: "W",
	name24: "X",
	name25: "Y",
	name26: "Z",
	/*
	name27: "African Wild Dog",
	name28: "Agama Lizard",
	name29: "Agouti",
	name30: "Ainu",
	name31: "Airedoodle",
	name32: "Akita",
	name33: "Alabai (Central Asian Shepherd)",
	name34: "Alaskan Klee Kai",
	name35: "Alaskan Pollock",
	name36: "Albacore Tuna",
	name37: "Albertonectes",
	name38: "Aldabra Giant Tortoise",
	name39: "Allosaurus",
	name40: "Alpaca",
	name41: "Alpine Goat",
	name42: "Amano Shrimp",
	name43: "Amazon Parrot",
	name44: "Amazon Tree Boa",
	name45: "Amberjack",
	name46: "American Alligator",
	name47: "American Bulldog",
	name48: "American Cocker Spaniel",
	name49: "American Coonhound",
	name50: "American Eel",
	name51: "American Foxhound",
	name52: "American Leopard Hound",
	name53: "American Pit Bull Terrier",
	name54: "American Pygmy Goat",
	name55: "American Staffordshire Terrier",
	name56: "American Water Spaniel",
	name57: "Amethystine Python",
	name58: "Amur Leopard",
	name59: "Anatolian Shepherd Dog",
	name60: "Andrewsarchus",
	name61: "Angelshark",
	name62: "Anglerfish",
	name63: "Anna’s Hummingbird",
	name64: "Anomalocaris",
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};