//module1.js 
let BLACChole =
{
	name1: "BLACChole",
	name2: "Asclepieion Of B.L.A.C.C.",
	name3: "Audio",
	name4: "B.L.A.C.C. Ark",
	name5: "BLACC Connect",
	name6: "BLACC Music",
	name7: "BLACC Telecommunication",
	name8: "Blacklining",
	name9: "Categories",
	name10: "Eye",
	name11: "Movies",
	name12: "Music",
	name13: "New Nexxus",
	name14: "NFT",
	name15: "OneiroNet",
	name16: "Pharaoh History",
	name17: "Upload",
	name18: "Videos",
	name19: "Vital Mathematics",
	name20: "Website Inquiry",
	name21: "Statistics - Mode",
	name22: "Statistics - Concepts Regarding The Mode",
	/*
	name23: "African Golden Cat",
	name24: "African Jacana",
	name25: "African Penguin",
	name26: "African Tree Toad",
	name27: "African Wild Dog",
	name28: "Agama Lizard",
	name29: "Agouti",
	name30: "Ainu",
	name31: "Airedoodle",
	name32: "Akita",
	name33: "Alabai (Central Asian Shepherd)",
	name34: "Alaskan Klee Kai",
	name35: "Alaskan Pollock",
	name36: "Albacore Tuna",
	name37: "Albertonectes",
	name38: "Aldabra Giant Tortoise",
	name39: "Allosaurus",
	name40: "Alpaca",
	name41: "Alpine Goat",
	name42: "Amano Shrimp",
	name43: "Amazon Parrot",
	name44: "Amazon Tree Boa",
	name45: "Amberjack",
	name46: "American Alligator",
	name47: "American Bulldog",
	name48: "American Cocker Spaniel",
	name49: "American Coonhound",
	name50: "American Eel",
	name51: "American Foxhound",
	name52: "American Leopard Hound",
	name53: "American Pit Bull Terrier",
	name54: "American Pygmy Goat",
	name55: "American Staffordshire Terrier",
	name56: "American Water Spaniel",
	name57: "Amethystine Python",
	name58: "Amur Leopard",
	name59: "Anatolian Shepherd Dog",
	name60: "Andrewsarchus",
	name61: "Angelshark",
	name62: "Anglerfish",
	name63: "Anna’s Hummingbird",
	name64: "Anomalocaris",
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};