//module1.js 
let Mathematical_Operations =
{
	name1: "Algebra",
	name2: "One Variable Equations and Inequalities",
	name3: "Linear Equations, Functions and Graphs",
	name4: "Sequences",
	name5: "System of Equations",
	name6: "---",
	name7: "Functions",
	name8: "Absolute Value Equations, Functions and Inequalities",
	name9: "Quadratic Equations and Functions",
	name10: "Polyomial Expressions, Equations and Functions",
	name11: "Exponential and Logarithmic Functions",
	name12: "Radical Equations and Functions",
	name13: "Rational Expressions, Equations and Functions",
	name14: "Algebra 1",
	name15: "Algebra Functions",
	name16: "Introduction To Variables",
	name17: "Substitution And Evaluating Expressions",
	name18: "Combining Like Terms",
	name19: "Introduction To Equivalent Experiences",
	name20: "Division By Zero",
	name21: "Solving Equations And Inequalities",
	name22: "Linear Equations With Variables On Both Sides",
	name23: "Linear Equations With Parentheses",
	name24: "Analyzing The Number Of Solutions To Linear Equations",
	name25: "Lineaar Equations With Unknown Coefficients",
	name26: "Multi-stwp Inequalities",
	name27: "Compound Inequalities",
	name28: "Working With Units",
	name29: "Rule Conversion",
	name30: "Appropriate Units",
	name31: "Word Problems With Multiple Units",
	name32: "Linear Equations And Graphs",
	name33: "Two-variable Linear Equation Introduction",
	name34: "Slope",
	name35: "Horizontal And Vertical Lines",
	name36: "X-intercept And Y-intercept",
	name37: "Applying Intercepts And Slope",
	name38: "Geometry",
	name39: "Area of Rectangle",
	name40: "Area of Triangle",
	name41: "Area of Circle",
	name42: "Trigonometry",
	name43: "Cosine",
	name44: "Sine",
	name45: "Tangent",
	name46: "cotangent",
	name47: "Secant",
	name48: "Cosecant",
	name49: "Statistics",
	name50: "Descriptive Statistics",
	name51: "Class Width",
	name52: "Class Midpoint",
	name53: "Terminology",
	name54: "Sample Mean",
	name55: "Mode Sample",
	name56: "Median",
	name57: "Organizing and Summarizing Data",
	name58: "Producing Data",
	name59: "Probability",
	name60: "Statistical Distributions",
	name61: "Random Variable",
	name62: "Binomial Distributionsi",
	name63: "Geometric Distributions",
	name64: "Sampling Distributions",
	name65: "Statistical Inference Overview",
	name66: "Inference With z Distributions",
	name67: "Inference with t Distributions",
	name68: "Inference for Populations",
	name69: "Chi Square Procedures",
	name70: "Linear Regression and Correlation",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
};