//module1.js 
let Physics =
{
	name1: "Motion In A Straight Line",
	name2: "Velocity",
	name3: "Acceleration",
	name4: "Distance, Velocity and Acceleration",
	name5: "Acceleration of Gravity",
	name6: "Falling Bodies",
	name7: "Projectile Motion",
	name8: "First Law Of Motion",
	name9: "Mass",
	name10: "Second Law Of Motion",
	name11: "Weight",
	name12: "British System Of Units",
	name13: "Free-Body Diagrams And Tension",
	name14: "Third Law Of Motion",
	name15: "Apparent Weight",
	name16: "Two And Third Dimensions",
	name17: "Static And Kinetic Friction",
	name18: "Coefficient Of Friction",
	name19: "Rolling Friction",
	name20: "Work",
	name21: "Power",
	name22: "Efficiency",
	name23: "Energy",
	name24: "Kinetic Energy",
	name25: "Potential Energy",
	name26: "Rest Energy",
	name27: "Conservation Of Energy",
	/*
	name28: "Agama Lizard",
	name29: "Agouti",
	name30: "Ainu",
	name31: "Airedoodle",
	name32: "Akita",
	name33: "Alabai (Central Asian Shepherd)",
	name34: "Alaskan Klee Kai",
	name35: "Alaskan Pollock",
	name36: "Albacore Tuna",
	name37: "Albertonectes",
	name38: "Aldabra Giant Tortoise",
	name39: "Allosaurus",
	name40: "Alpaca",
	name41: "Alpine Goat",
	name42: "Amano Shrimp",
	name43: "Amazon Parrot",
	name44: "Amazon Tree Boa",
	name45: "Amberjack",
	name46: "American Alligator",
	name47: "American Bulldog",
	name48: "American Cocker Spaniel",
	name49: "American Coonhound",
	name50: "American Eel",
	name51: "American Foxhound",
	name52: "American Leopard Hound",
	name53: "American Pit Bull Terrier",
	name54: "American Pygmy Goat",
	name55: "American Staffordshire Terrier",
	name56: "American Water Spaniel",
	name57: "Amethystine Python",
	name58: "Amur Leopard",
	name59: "Anatolian Shepherd Dog",
	name60: "Andrewsarchus",
	name61: "Angelshark",
	name62: "Anglerfish",
	name63: "Anna’s Hummingbird",
	name64: "Anomalocaris",
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};