//module1.js 
let Coding =
{
	name1: "Image Text Blocks",
	name2: "Image Text",
	name3: "Image Effects",
	name4: "Image Overlay Icon",
	name5: "Image Overlay Title",
	name6: "Image Overlay Zoom",
	name7: "Image Overlay Slide",
	name8: "Image Overlay Fade",
	name9: "Tab Gallery",
	name10: "Image Gallery",
	name11: "Image Grid",
	name12: "Lightbox",
	name13: "Modal Images",
	name14: "Slideshow Gallery",
	name15: "Slideshow",
	name16: "Responsive Header",
	name17: "Pill Navigation",
	name18: "Slicky Social Bar",
	name19: "Vertical Button Group",
	name20: "Button Group",
	name21: "Breadcrumbs",
	name22: "Pagination",
	name23: "Collapsed Sidepanel",
	name24: "Collapsed Sidebar",
	name25: "Curtain Menu",
	name26: "Mobile Menu",
	name27: "Mega Menu",
	name28: "Dropup",
	name29: "Subnavigation Menu",
	name30: "Dropdown In Sidenav",
	name31: "Dropdown In Topnav",
	name32: "Cascade Dropdowns",
	name33: "Click Dropdowns",
	name34: "Hover Dropdowns",
	name35: "Navbar On Image",
	name36: "Shrink Navbar On Scroll",
	name37: "Hide Navbar On Scroll",
	name38: "Slide Down Bar On Scroll",
	name39: "Fixed Menu",
	name40: "Equal Width Menu Links",
	name41: "Centered Menu Link",
	name42: "Right Aligned Menu Links",
	name43: "Button Border Nav Links",
	name44: "Responsive Button Nav",
	name45: "Button Navigation",
	name46: "Vertical Menu",
	name47: "Horizontal Scroll Menu",
	name48: "Sidebar With Icons",
	name49: "Hover Sidenav Button",
	name50: "Off-canvas Menu",
	name51: "Fullscreen Navigation",
	name52: "Responsive Sidebar",
	name53: "Side Navigation",
	name54: "Fixed Sidebar",
	name55: "Search Bar",
	name56: "Search Menu",
	name57: "Navbar With Icons",
	name58: "Split Navigation",
	name59: "Responsive Topnav",
	name60: "Top Navigation",
	name61: "Hover Tabs",
	name62: "Full Page Tabs",
	name63: "Tab Headers",
	name64: "Vertical Tabs",
	name65: "Tabs",
	name66: "Accordion",
	name67: "Menu Icon",
	name68: "Toggle Hide Show",
	name69: "Working Window",
	name70: "Video",
	name71: "User Rating",
	name72: "To Do List",
	name73: "Snack Bar",
	name74: "Skill Bar",
	name75: "Icon Bar",
	name76: "Replace Document",
	name77: "Progress Bar",
	name78: "Profile Card",
	name79: "Page Transition",
	name80: "Overlay",
	name81: "Multiple Form",
	name82: "Login",
	name83: "Loader",
	name84: "Flip Card",
	name85: "File Upload",
	name86: "Enter Control",
	name87: "Sticky Navbar",
	name88: "Scrollable Image Gallery",
	name89: "Responsive Navbar Dropdown",
	name90: "Responsive Image Grid",
	name91: "Dark Mode",
	name92: "Countdown",
	name93: "Continuous Update Of Information",
	name94: "Comparison Table",
	name95: "Class Width",
	name96: "Checkout Form",
	name97: "Callout Box",
	name98: "Black And White Image",
};