//module1.js 
let Book =
{
	name1: "A.S.E. Manual",
	name2: "Algebra 1 Topics",
	name3: "Zebra Labyrinth",
	name4: "Lesser Keys Of Solomon",
	name5: "Arthneya's Memory Pathway",
		/*

	name6: "........",
	name7: "Arthneya's Breakdown",
	name8: "African Bush Elephant",
	name9: "African Clawed Frog",
	name10: "African Forest Elephant",
	name11: "African Grey Parrot",
	name12: "African Palm Civet",
	name13: "African Sugarcane Borer",
	name14: "Aardwolf",
	name15: "Abyssinian Guinea Pig",
	name16: "Achrioptera Manga",
	name17: "Addax",
	name18: "Admiral Butterfly",
	name19: "Affenpinscher",
	name20: "African Bullfrog",
	name21: "African Civet",
	name22: "African Fish Eagle",
	name23: "African Golden Cat",
	name24: "African Jacana",
	name25: "African Penguin",
	name26: "African Tree Toad",
	name27: "African Wild Dog",
	name28: "Agama Lizard",
	name29: "Agouti",
	name30: "Ainu",
	name31: "Airedoodle",
	name32: "Akita",
	name33: "Alabai (Central Asian Shepherd)",
	name34: "Alaskan Klee Kai",
	name35: "Alaskan Pollock",
	name36: "Albacore Tuna",
	name37: "Albertonectes",
	name38: "Aldabra Giant Tortoise",
	name39: "Allosaurus",
	name40: "Alpaca",
	name41: "Alpine Goat",
	name42: "Amano Shrimp",
	name43: "Amazon Parrot",
	name44: "Amazon Tree Boa",
	name45: "Amberjack",
	name46: "American Alligator",
	name47: "American Bulldog",
	name48: "American Cocker Spaniel",
	name49: "American Coonhound",
	name50: "American Eel",
	name51: "American Foxhound",
	name52: "American Leopard Hound",
	name53: "American Pit Bull Terrier",
	name54: "American Pygmy Goat",
	name55: "American Staffordshire Terrier",
	name56: "American Water Spaniel",
	name57: "Amethystine Python",
	name58: "Amur Leopard",
	name59: "Anatolian Shepherd Dog",
	name60: "Andrewsarchus",
	name61: "Angelshark",
	name62: "Anglerfish",
	name63: "Anna’s Hummingbird",
	name64: "Anomalocaris",
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};