//module1.js 
let BLACC_Connect =
{
	name1: "BLACC Connect",
	name2: "How many states are Incorporated within black connect",
	name3: "Open Black connect",
	name4: "What states are Incorporated within black connect",
	name5: "Which states in the South are Incorporated within black connect",
	name6: "Which states in the West are Incorporated within black connect",
	name7: "Which states in the Midwest are Incorporated within black connect",
	name8: "Which states in the Northeast are Incorporated within black connect",
	name9: "What are the time zones",
	name10: "Open California",
	name11: "What counties in California are Incorporated within black connect",
	name12: "How many counties in California are Incorporated within black connect",
	name13: "What counties are within California",
	name14: "What is the wealthiest district in Los Angeles",
	name15: "----Alhambra, CA-----",
	name16: "Alhambra - Agriculture",
	name17: "Alhambra - Business Mentoring",
	name18: "Alhambra - Civil Volunteering",
	name19: "Alhambra - Education",
	name20: "Alhambra - Family",
	name21: "Alhambra - Family Resources",
	name22: "Alhambra - Finances",
	name23: "Alhambra - Food And Clothing",
	name24: "Alhambra - For-profit",
	name25: "Alhambra - Gambling",
	name26: "Alhambra - Government Resources",
	name27: "Alhambra - Health And Medical",
	name28: "Alhambra - Housing",
	name29: "Alhambra - Insurance",
	name30: "Alhambra - Labor",
	name31: "Alhambra - Mentorship",
	name32: "Alhambra - Modeling",
	name33: "Alhambra - Music",
	name34: "Alhambra - Non-profit",
	name35: "Alhambra - Private Contractor",
	name36: "Alhambra - Probation And Parole",
	name37: "Alhambra - Professional Mentoring",
	name38: "Alhambra - Public Contractor",
	name39: "Alhambra - Public",
	name40: "Alhambra - Public Resources",
	name41: "Alhambra - Revenue And Tax Advisory",
	name42: "Alhambra - Highway Construction",
	name43: "Alhambra - Technical Trade",
	name44: "Alhambra - Technology",
	name45: "Alhambra - Theater",
	name46: "Alhambra - Transportation",
	name47: "Alhambra - Utilities",
	name48: "Alhambra - Vehicle",
	name49: "Alhambra - Water",
	name50: "Alhambra - Data",
	name51: "American Foxhound",
	name52: "American Leopard Hound",
	name53: "American Pit Bull Terrier",
	name54: "American Pygmy Goat",
	name55: "American Staffordshire Terrier",
	name56: "American Water Spaniel",
	name57: "Amethystine Python",
	name58: "Amur Leopard",
	name59: "Anatolian Shepherd Dog",
	name60: "Andrewsarchus",
	name61: "Angelshark",
	name62: "Anglerfish",
	name63: "Anna’s Hummingbird",
	name64: "Anomalocaris",
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
};