//module1.js 
let Conversions =
{
	name1: "Inches To Centimeters",
	name2: "Feet To Meter",
	name3: "Yards To Meter",
	name4: "Miles To Kilometers",
	name5: "Millimeter To Inches",
	name6: "Centimeter To Inches",
	name7: "Meters To Feet",
	name8: "Meters To Yards",
	name9: "Kilometers To Miles",
	name10: "Square Feet To Square Meters",
	name11: "Square Yards To Square Meters",
	name12: "Square Miles To Square Kilometers",
	name13: "Square Kilometers To Square Miles",
	name14: "Hectacres To Acres",
	name15: "Pints To Liters",
	name16: "Quarts To Liters",
	name17: "Gallons To Liters",
	name18: "Liters To Pints",
	name19: "Liters To Quarts",
	name20: "Liters To Gallons",
	name21: "Ounces To Grams",
	name22: "Pounds To Kilograms",
	name23: "Kilograms To Pounds",
	name24: "Metric Tons to Short Tons",
	name25: "Fahrenheit To Celsius",
	name26: "Fahrenheit To Kelvin",
	name27: "Celsius To Fahrenheit",
	name28: "Celsius To Kelvin",
	name29: "Kelvin To Celsius",
	name30: "Kelvin To Fahrenheit",
	/*
	name31: "Airedoodle",
	name32: "Akita",
	name33: "Alabai (Central Asian Shepherd)",
	name34: "Alaskan Klee Kai",
	name35: "Alaskan Pollock",
	name36: "Albacore Tuna",
	name37: "Albertonectes",
	name38: "Aldabra Giant Tortoise",
	name39: "Allosaurus",
	name40: "Alpaca",
	name41: "Alpine Goat",
	name42: "Amano Shrimp",
	name43: "Amazon Parrot",
	name44: "Amazon Tree Boa",
	name45: "Amberjack",
	name46: "American Alligator",
	name47: "American Bulldog",
	name48: "American Cocker Spaniel",
	name49: "American Coonhound",
	name50: "American Eel",
	name51: "American Foxhound",
	name52: "American Leopard Hound",
	name53: "American Pit Bull Terrier",
	name54: "American Pygmy Goat",
	name55: "American Staffordshire Terrier",
	name56: "American Water Spaniel",
	name57: "Amethystine Python",
	name58: "Amur Leopard",
	name59: "Anatolian Shepherd Dog",
	name60: "Andrewsarchus",
	name61: "Angelshark",
	name62: "Anglerfish",
	name63: "Anna’s Hummingbird",
	name64: "Anomalocaris",
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};