//module1.js 
let Neurobiology_Research =
{
	name1: "Axon",
	name2: "Drug Effect",
	name3: "Sites Of Action",
	name4: "Pharmacology Kinetics",
	name5: "Intraperitoneal Injection",
	name6: "Intramuscular Injection",
	name7: "Subcutaneous Injection",
	name8: "Oral Administration",
	name9: "Inhalation",
	name10: "Topical Administration",
	name11: "Intracerebral Administration",
	name12: "Depot Binding",
	name13: "Dose Response Curve",
	name14: "Therapeutic Index",
	name15: "Affinity",
	name16: "Tolerance",
	name17: "Sensitization",
	name18: "Withdrawal Symptom",
	name19: "Antagonist",
	name20: "Agonist",
	name21: "Direct Agonist",
	name22: "Receptor Blocker",
	name23: "Direct Antagonist",
	name24: "Noncompetitive Binding",
	name25: "Indirect Antagonist",
	name26: "Presynaptic Heteroreceptor",
	name27: "C H A T",
	name28: "Botulinum Toxin",
	name29: "Black Widow Spider Venom",
	name30: "Hemicholinum",
	name31: "Neostigmine",
	name32: "Muscarinic Receptor",
	name33: "Atropine",
	name34: "Curare",
	name35: "L D O P A",
	name36: "Nigrostriatal System",
	name37: "Mesolimbic System",
	name38: "Mesocortical System",
	name39: "Parkison’s Disease",
	name40: "A M P T",
	name41: "Reserpine",
	name42: "Apomorphine",
	name43: "Methylphenidate",
	name44: "Monoamine Oxidase",
	name45: "Chlorpromazine",
	name46: "N E",
	name47: "Epinephrine",
	name48: "Methylphenidate",
	name49: "Moclobemide",
	name50: "Locus Coeruleus",
	name51: "Axonal Varicosity",
	name52: "Idazoxan",
	name53: "Serotonin",
	name54: "P C P A",
	name55: "Fluoxetine",
	name56: "Fenfluramine",
	name57: "L S D",
	name58: "M D M A",
	name59: "Glutamate",
	name60: "N M D A Receptor",
	name61: "A M P A Receptor",
	name62: "Kainate Receptor",
	name63: "Metabotropic Glutamate Receptor",
	name64: "A P 5",
	name65: "P C P", 
	/*
	name66: "G A B A",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};