//module1.js 
let Politicians =
{
	name1: "Eduardo Garcia",
	name2: "David Alveraz",
	name3: "Tasha Boarner",
	name4: "Laurie Davies",
	name5: "Brain Maienschein",
	name6: "Maries Waldron",
	name7: "Christopher Ward",
	name8: "Akilah Weber",
	name9: "Rick Chavez Zubar",
	name10: "Isaac Bryan",
	name11: "Pilar Shiavo",
	name12: "Lisa Caldron",
	name13: "Juan Carrillo",
	name14: "Wendy Carrillo",
	name15: "Mike Fong",
	name16: "Laura Friedman",
	name17: "Jesse Gabriel",
	name18: "Mike Gipson",
	name19: "Chris Holden",
	name20: "Jacqui Irwin",
	name21: "Reginald Bryon Jones-Sawyer",
	name22: "Tom Lackey",
	name23: "Josh Lowenthal",
	name24: "Tina Mckinnor",
	name25: "Al Muratsuchi",
	name26: "Blanca Pacheco",
	name27: "Sharon Quirk-Silva",
	name28: "Anthony Rendon",
	name29: "Luz Rivas",
	name30: "Freddie Rodriguez",
	name31: "Blanca Rubio",
	name32: "Miguel Santiago",
	/*
	name33: "Alabai (Central Asian Shepherd)",
	name34: "Alaskan Klee Kai",
	name35: "Alaskan Pollock",
	name36: "Albacore Tuna",
	name37: "Albertonectes",
	name38: "Aldabra Giant Tortoise",
	name39: "Allosaurus",
	name40: "Alpaca",
	name41: "Alpine Goat",
	name42: "Amano Shrimp",
	name43: "Amazon Parrot",
	name44: "Amazon Tree Boa",
	name45: "Amberjack",
	name46: "American Alligator",
	name47: "American Bulldog",
	name48: "American Cocker Spaniel",
	name49: "American Coonhound",
	name50: "American Eel",
	name51: "American Foxhound",
	name52: "American Leopard Hound",
	name53: "American Pit Bull Terrier",
	name54: "American Pygmy Goat",
	name55: "American Staffordshire Terrier",
	name56: "American Water Spaniel",
	name57: "Amethystine Python",
	name58: "Amur Leopard",
	name59: "Anatolian Shepherd Dog",
	name60: "Andrewsarchus",
	name61: "Angelshark",
	name62: "Anglerfish",
	name63: "Anna’s Hummingbird",
	name64: "Anomalocaris",
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};