//module1.js 
let Computer_Research =
{
	name1: "Linux",
	name2: "date",
	name3: "cal",
	name4: "df",
	name5: "free",
	name6: "pwd",
	name7: "cd",
	name8: "ls",
	name9: "less",
	name10: "cp -u*",
	name11: "mv",
	name12: "type",
	name13: "which",
	name14: "help",
	name15: "man",
	name16: "aprop",
	name17: "whatis",
	name18: "info",
	name19: "alias",
	name20: "cat",
	name21: "R",
	name22: "Node.js",
	name23: "Excel",
	name24: "CSS",
	name25: "background",
	name26: "background-color",
	name27: "background-image",
	name28: "background-position",
	name29: "background-repeat",
	name30: "HTML",
	name31: "a tag",
	name32: "area tag",
	name33: "article tag",
	name34: "audio tag",
	name35: "bgsound tag",
	name36: "br tag",
	name37: "button tag",
	name38: "div tag",
	name39: "footer tag",
	name40: "form tag",
	name41: "h1 tag",
	name42: "head tag",
	name43: "header tag",
	name44: "hr tag",
	name45: "html tag",
	name46: "img tag",
	name47: "link tag",
	name48: "map tag",
	name49: "nav tag",
	name50: "p tag",
	name51: "pre tag",
	name52: "section tag",
	name53: "span tag",
	name54: "style tag",
	name55: "target atrribute",
	name56: "td tag",
	name57: "th tag",
	name58: "title tag",
	name59: "tr tag",
	name60: "ul tag",
	name61: "JavaScript",
	name62: "Asynchronous Programming Part 1",
	name63: "Bugs And Errors Part 1",
	name64: "Data Structures Objects And Arrays Part 1",
	/*
	name65: "Antarctic Scale Worm",
	name66: "Antelope",
	name67: "Antiguan Racer Snake",
	name68: "Apennine Wolf",
	name69: "Apple Head Chihuahua",
	name70: "Arabian Cobra",
	name71: "Arafura File Snake",
	name72: "Arapaima",
	name73: "Archaeopteryx",
	*/
};